to_do_app/urls.py
from django.urls import path
from to_do_app.views import (TaskListView,
                             TaskCreateView,
                             TaskUpdateView,
                             TaskDeleteView,
                             TagListView,
                             TagCreateView,
                             TagUpdateView,
                             TagDeleteView,
                             task_complete,
                             task_undo)

urlpatterns = [
    path("", TaskListView.as_view(), name="task_list"),
    path("task/create/", TaskCreateView.as_view(), name="task_create"),
    path("task/<int:pk>/update/", TaskUpdateView.as_view(), name="task_update"),
    path("task/<int:pk>/delete/", TaskDeleteView.as_view(), name="task_delete"),
    path("task/<int:pk>/complete/", task_complete, name="task_complete"),
    path("task/<int:pk>/undo/", task_undo, name="task_undo"),
    path("tags/", TagListView.as_view(), name="tags_list"),
    path("tags/create/", TagCreateView.as_view(), name="tag_create"),
    path("tag/<int:pk>/update/", TagUpdateView.as_view(), name="tag_update"),
    path("tag/<int:pk>/delete/", TagDeleteView.as_view(), name="tag_delete"),
]

app_name = "to_do_app"

to_do_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("to_do_app.urls", namespace="to_do_app")),
]

to_do_app/models.py
from django.db import models


class Tag(models.Model):
    name = models.TextField(max_length=25, unique=True)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.TextField(max_length=500)
    datetime = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(blank=True, null=True)
    done = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag)

    class Meta:
        ordering = ["done", "-datetime"]

to_do_app/forms.py
from django import forms
from django.utils.timezone import localtime, now

from .models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ("content", "deadline", "tags")
        widgets = {
            'deadline': forms.DateTimeInput(attrs={
                'type': 'datetime-local',
                'min': localtime(now()).strftime('%Y-%m-%dT%H:%M'),
            }),
            'tags': forms.CheckboxSelectMultiple(),
        }

to_do_app/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from to_do_app.forms import TaskForm
from to_do_app.models import Task, Tag


class TaskListView(ListView):
    model = Task
    context_object_name = "task_list"
    template_name = "to_do_app/home.html"


class TaskCreateView(CreateView):
    model = Task
    form_class = TaskForm
    template_name = "to_do_app/task_create.html"
    success_url = reverse_lazy("to_do_app:task_list")


class TaskUpdateView(UpdateView):
    model = Task
    form_class = TaskForm
    template_name = "to_do_app/task_create.html"
    success_url = reverse_lazy("to_do_app:task_list")


class TaskDeleteView(DeleteView):
    model = Task
    success_url = reverse_lazy("to_do_app:task_list")
    template_name = "to_do_app/delete.html"


def task_complete(request, pk):
    task = get_object_or_404(Task, pk=pk)
    task.done = True
    task.save()
    return redirect("to_do_app:task_list")


def task_undo(request, pk):
    task = get_object_or_404(Task, pk=pk)
    task.done = False
    task.save()
    return redirect("to_do_app:task_list")


class TagListView(ListView):
    model = Tag
    context_object_name = "tag_list"
    template_name = "to_do_app/tag_list.html"


class TagCreateView(CreateView):
    model = Tag
    fields = ("name",)
    template_name = "to_do_app/tag_create.html"
    success_url = reverse_lazy("to_do_app:tags_list")


class TagUpdateView(UpdateView):
    model = Tag
    fields = ("name",)
    template_name = "to_do_app/tag_create.html"
    success_url = reverse_lazy("to_do_app:tags_list")


class TagDeleteView(DeleteView):
    model = Tag
    template_name = "to_do_app/delete.html"
    success_url = reverse_lazy("to_do_app:tags_list")

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
  <meta charset="UTF-8">
  <title>To Do List</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <link rel="stylesheet" href="/static/css/styles.css">
</head>
<body>
  <div class="container">
    <div class="row">
      <div class="col-sm-3">
        {% block sidebar %}
          {% include "includes/sidebar.html" %}
        {% endblock %}
      </div>
    
      <div class="col-sm-9">
        {% block content %}
        {% endblock %}
      </div>
    </div>
  </div>

</body>
</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item">
    <a href="/">Home</a>
  </li>
  <li class="list-group-item">
    <a href="{% url 'to_do_app:tags_list' %}">Tags</a>
  </li>
</ul>

templates/to_do_app/delete.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <form action="" method="post" novalidate>
    {% csrf_token %}
    <h2>Are you sure?</h2>
    <input type="submit" value="Delete" class="btn btn-danger">
    <input type="button" onclick="history.back();" value="Cancel" class="btn btn-secondary">
  </form>
  
{% endblock %}

templates/to_do_app/home.html
{% extends "base.html" %}
{% block content %}
  <h1>TODO LIST</h1>
  <a href="{% url 'to_do_app:task_create' %}" class="btn btn-primary">Add task</a>
  {% for task in task_list %}
    <div class="task-block">
      <div>
        <h5>
          {{ task.content }}
          {% if task.done %}
            <span style="color: green">Done</span>
          {% else %}
            <span style="color: red">Not done</span>
          {% endif %}
        </h5>
        <p>
          Created: {{ task.datetime }}
        </p>
        {% if task.deadline %}
          <p>Deadline: {{ task.deadline }}</p>
        {% endif %}
        {% if task.tags.exists %}
          <p>Tags:
            {% for tag in task.tags.all %}
              {{ tag.name }}
            {% endfor %}
          </p>
        {% endif %}
      </div>
      <div>
        {% if task.done %}
          <a href="{% url 'to_do_app:task_undo' task.id %}" class="btn btn-warning">Undo</a>
        {% else %}
          <a href="{% url 'to_do_app:task_complete' task.id %}" class="btn btn-success">Complete</a>
        {% endif %}
        <a href="{% url 'to_do_app:task_update' pk=task.id %}" class="btn btn-secondary">Update</a>
        <a href="{% url 'to_do_app:task_delete' pk=task.id %}" class="btn btn-danger">Delete</a>
      </div>
    </div>
    
  {% endfor %}
{% endblock %}

templates/to_do_app/tag_create.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="{{ object|yesno:"Update, Create" }}" class="btn btn-success">
  </form>
{% endblock %}

templates/to_do_app/tag_list.html
{% extends "base.html" %}
{% block content %}
  <h1>Tags</h1>
  <a href="{% url 'to_do_app:tag_create' %}" class="btn btn-primary">Add tag</a>
  <table class="table">
    <tr>
      <th>Name</th>
      <th>Update</th>
      <th>Delete</th>
    </tr>
    {% for tag in tag_list %}
      <tr>
        <td>{{ tag.name }}</td>
        <td>
          <a href="{% url 'to_do_app:tag_update' pk=tag.id %}" class="btn btn-secondary">Update</a>
        </td>
        <td>
          <a href="{% url 'to_do_app:tag_delete' pk=tag.id %}" class="btn btn-danger">Delete</a>
        </td>
      </tr>
    {% endfor %}
  </table>
  
{% endblock %}

templates/to_do_app/task_create.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="{{ object|yesno:"Update, Create" }}" class="btn btn-success">
  </form>
{% endblock %}

templates/to_do_app/task_delete.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <form action="" method="post" novalidate>
    {% csrf_token %}
    <h2>Are you sure?</h2>
    <input type="submit" value="Delete" class="btn btn-danger">
    <input type="button" onclick="history.back();" value="Cancel" class="btn btn-secondary">
  </form>
  
{% endblock %}